apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: iu4-dev-wildcard
spec:
  secretName: iu4-dev-wildcard-tls
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  dnsNames:
    - iu4.dev
    - "*.iu4.dev"
