apiVersion: batch/v1
kind: Job
metadata:
  name: create-transfersh-bucket
spec:
  backoffLimit: 6
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: mc
          image: minio/mc
          command: ["/bin/sh", "-c"]
          args:
            - |
              mc alias set myminio http://s3-transfersh-service:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
              mc mb --ignore-existing myminio/transfersh
              mc ls myminio
          env:
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-transfersh-secret
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-transfersh-secret
                  key: secretkey
