apiVersion: v1
kind: Secret
metadata:
  name: {{ include "transfersh.fullname" . }}-minio
type: Opaque
stringData:
  accesskey: {{ .Values.minio.rootUser | quote }}
  secretkey: {{ .Values.minio.rootPassword | quote }}
